server {
    listen 80;

    # Servir la app React (build estático)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api/* → backend FastAPI (igual que vite proxy en dev)
    # Se elimina el prefijo /api antes de reenviar, igual que vite hace con rewrite
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
